CREATE TABLE `flip_observation` (
  `id` VARCHAR(191) NOT NULL,
  `itemId` INTEGER NOT NULL,
  `rankingView` VARCHAR(191) NOT NULL,
  `modelVersion` VARCHAR(191) NOT NULL,
  `observedAt` DATETIME(3) NOT NULL,
  `bucketAt` DATETIME(3) NOT NULL,
  `horizonEndsAt` DATETIME(3) NOT NULL,
  `rank` INTEGER NOT NULL,
  `buyPrice` INTEGER NOT NULL,
  `sellPrice` INTEGER NOT NULL,
  `netProfit` INTEGER NOT NULL,
  `estimatedUnitsPerHour` DOUBLE NOT NULL,
  `estimatedGpPerHour` DOUBLE NOT NULL,
  `confidence` DOUBLE NOT NULL,
  `features` JSON NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'pending',
  `outcome` VARCHAR(191) NULL,
  `entryTouchedAt` DATETIME(3) NULL,
  `exitTouchedAt` DATETIME(3) NULL,
  `timeToCompletionMinutes` INTEGER NULL,
  `proxyGpPerHour` DOUBLE NULL,
  `resolvedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `flip_observation_modelVersion_bucketAt_itemId_key`(`modelVersion`, `bucketAt`, `itemId`),
  INDEX `flip_observation_status_horizonEndsAt_idx`(`status`, `horizonEndsAt`),
  INDEX `flip_observation_modelVersion_observedAt_idx`(`modelVersion`, `observedAt`),
  INDEX `flip_observation_itemId_observedAt_idx`(`itemId`, `observedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
